### ISSUE TITLE
BulkInsert ennd up Inserting same Object record multiple times when some Object properties are equal.

### ISSUE THREAD

**Issue by jometho** [bytefish/bytefish.de#13]
I have a List<MyObject> objects= new MyObject(name, descr, type, prop4); 
I have noticed in some cases when some properties of the of different given object instance are the same, BulInsert re-uses the previous instance values.

For Instance, I have;
myObject1 with name="vector_db", descr="xxxxxx",type="postgis (JNDI)", otherProps="unique prop1";
myObject2 with name="vector_db", descr="xxxxxx",type="postgis (JNDI)", otherProps="unique prop2";
myObject3 with name="vector_db", descr="xxxxxx",type="postgis (JNDI)", otherProps="unique prop3";

myObject4 with name="client_db", descr="xxxxxx",type="postgis", otherProps="unique prop";

In the database, the final data inserted for myObject1,myObject2 and myObject3 is the same despite the fact that otherProps is not suppose to be the same.

What strategy does BukInsert use that makes it insert the same record multiple times when and then it ignores other records?

**Comment by jometho** [comment]
I believe this issue is related to synchronization in saveEntity() method, ehre the saveEntity seems to be reading the same value from the PgBinaryWriter each time for some records...

**Comment by bytefish** [comment]
First of all thanks for filing an issue.

Could you please create the issue in the PgBulkInsert Issue Tracker: 

* https://github.com/bytefish/PgBulkInsert/issues

Also add the following information:

* Which PgBulkInsert Version are you using?
* Which PostgreSQL Version are you using?

It would be perfect, if you have a Test or Code Snippet, that shows how to reproduce the issue.

Access to the ``PgBinaryWriter`` is synchronized, so that shouldn't be the issue: 

* https://github.com/bytefish/PgBulkInsert/blob/8de1a733def9d74c2a3fe23b4c59a9af2f2a8549/PgBulkInsert/src/main/java/de/bytefish/pgbulkinsert/PgBulkInsert.java#L58

**Comment by bytefish** [comment]
I wrote a Unit Test in Issue:

* https://github.com/bytefish/PgBulkInsert/issues/23

But I cannot reproduce the behavior. If you succeed in making this test fail, please feel free to reopen the Ticket.
