### ISSUE TITLE
FCM with GoogleCredentials and SOCKs proxy

### ISSUE THREAD

**Issue by lucvanqui** [bytefish/bytefish.de#18]
Hi,
Could we use fcm-java to sign to FCM server with GoogleCredetial json file when I get from FCM server ?
And how about using SOCKs Proxy in fcm-java ?

@Test
    public void testFcmClientWithProxySettings() {

        // Create Settings:
        IFcmClientSettings settings = new MockFcmClientSettings();

        // Create the HttpClient:
        HttpClient httpClient = new HttpClient(settings);

        // And configure the HttpClient:
        httpClient.configure((httpClientBuilder -> {

            // Define the Credentials to be used:
            BasicCredentialsProvider basicCredentialsProvider = new BasicCredentialsProvider();

            // Set the Credentials (any auth scope used):
            basicCredentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials("your_username", "your_password"));

            // Now configure the HttpClientBuilder:
            httpClientBuilder
                    // Set the Proxy Address:
                    .setProxy(new HttpHost("your_hostname", 1234))
                    // Set the Authentication Strategy:
                    .setProxyAuthenticationStrategy(new ProxyAuthenticationStrategy())
                    // Set the Credentials Provider we built above:
                    .setDefaultCredentialsProvider(basicCredentialsProvider);
        }));

        // Finally build the FcmClient:
        IFcmClient client = new FcmClient(settings, httpClient);
    }

I refer this test and put them in my case with Socks proxy and Json google credetial

Please give me the suggestion in this case.
 
Thanks,
Qui

**Comment by bytefish** [comment]
@lucvanqui FcmJava uses the Legacy HTTP Protocol, that's why I made the Repository read-only. You probably want to switch to the Official Firebase Admin SDK for Java, which supports Messaging by now (https://firebase.google.com/docs/admin/setup).

If you want to continue to use FcmJava, then you have to configure the HttpClient as seen in the Unit Test above. For the specific configuration for your setup you should read the documentation on Apache HttpComponents, because that's what used in FcmJava for HTTP Communication:

* http://hc.apache.org/
