### ISSUE TITLE
Follow up on flight data analysis post comparing Neo4j and SQL Server 2017

### ISSUE THREAD

**Issue by dmathew** [bytefish/bytefish.de#28]
Were you able to figure out why there were differences in:
* the query results?, and
* the performance of the queries?

I am referring to this post: https://bytefish.de/blog/sql_server_2017_graph_database/

Thanks!

**Comment by bytefish** [comment]
Thanks for your interest!

Not really. @jexp has shared some insights and hints here:

* https://github.com/bytefish/bytefish.de/issues/9
* https://github.com/bytefish/bytefish.de/issues/10

I recently ran the experiments again on a SSD, but it didn't change the results. I also haven't been able to look into why some results are missing in the final query. I bet it is due to my "homegrown" JSON generator and could be fixed using more stable .NET clients.

**Comment by dmathew** [comment]
Thanks for the reply. I had seen one of those threads earlier; it's helpful to have the context provided by the information from these other threads.

On a related note, would you mind posting some sample screenshots of how the visualization of your graph implementation with SQL Server 2019 CTP looks? I am referring to a later post: https://bytefish.de/blog/sql_server_2019_graph_database/.

**Comment by bytefish** [comment]
I have only experimented with the Graph in the example post, which should be more or less the model of the first post. Originally I wanted to also visualize the query results, but it turned out to be too complicated. 😢

**Comment by dmathew** [comment]
No problem. I'm sure it would be complicated. 
Thank you for the replies and for sharing your findings!
