### ISSUE TITLE
For the project https://bytefish.de/blog/fcmsharp/

### ISSUE THREAD

**Issue by bgcnet** [bytefish/bytefish.de#31]
Hello,

Can you add the possibility to resend again a failed message ?
For example, Firebase supports max 4K of message length and if I have a list of many numeric ids I should split them in a for statement like this :

        public static void SendIds(IEnumerable<int> ids, string operationType, string topicModel)
        {
            for (int i = 0; i < ids.Count(); i = i + 100)
            {
                var items = ids.Skip(i).Take(100);
                var idsDict = new List<Dictionary<string, string>>();
                idsDict.Add(new Dictionary<string, string>() { { "type", operationType }, { "ids", string.Concat("[" + string.Join(",", items.ToArray()) + "]") } });
                Task.Run(() => SendAsyncFcmMessage(idsDict[0], topicModel));
            }
        }

My question is that if it fails for an interval of 100 ids, I want to submit again for this interval.
I can see you have FcmHttpClient and here it returns
return JsonConvert.DeserializeObject<TResponseType>(httpResponseContentAsString);

But I think I need HttpResponseMessage httpResponseMessage in return because it has a property IsSuccessStatusCode which can be true/false.

**Comment by bytefish** [comment]
@bgcnet Thanks for your interest in this project, but I have archived the repository and it won't be updated. 

It's because: Messaging Features have been added to the Firebase Admin SDK for .NET lately, so you should use the official Firebase Admin SDK for .NET instead of FcmSharp:

* https://github.com/firebase/firebase-admin-dotnet

Again, thanks for your interest! 🙏

And I hope you understand, that the official client should be used instead.
