### ISSUE TITLE
Question on dynamic load of the data source

### ISSUE THREAD

**Issue by VivekMittals** [bytefish/bytefish.de#41]
Hello Phillip,

First of all thanks for such a descriptive article on the multi tenant support.

I had a few queries with respect to the article and would like to know your thoughts on the same:

During dynamic load I suspect there might be a condition where while updating the configuration we might end up in a case where any specific transaction can get impacted in case a data source connection is closed.

I just tried running some junits which actually led me to this behaviour.. so I suspect a lock while doing an update would be required. Please correct me if you think this is not right?

Also I wanted to understand the role of AsyncConfig.java? I might be missing some very basic trick here but when I tried running the original code and found that in case an automated junit is run then this class causes an error as the tenant name is never set and hence there is no datasource that can be found for null. Hence the application start up fails.

Again thank you for your time and effort in this article.
Thanks
Vicky

**Comment by bytefish** [comment]
Yes, I think right now I am doing a close on the HikariCP Connection Pool. I did a quick look at the HikariCP Issue tracker and there is a way to soft evict the connections, when shutting down the Connection Pool. This might be worth implementing or adding to the article:

* https://github.com/brettwooldridge/HikariCP/issues/742#issuecomment-275286877

For the Tenant Name. I think I really should add something like a default tenant for the Spring Boot startup. See... I don't know how you start up your application. I went great length to prevent Spring Boot magic from making connections to the database, when starting the application. It's because: If Spring Boot tries to automagically find out, which database and dialect you are using, and other things... thereby making connections to a database.

But this connection at Startup, which Tenant Database should it use? The first?

So this can easily be fixed, if you are setting a Tenant Name explicitly for booting the application by using the ThreadLocal implementation I have provided. I will add this to the article, because it's not obvious at all. If you set this Tenant and Spring Boot makes a database connection at startup, it will use this tenant and not err out.

**Comment by bytefish** [comment]
The ``AsyncConfig`` is used for passing the tenant name into child threads when using the Spring ``@Async`` annotation.

**Comment by VivekMittals** [comment]
Thanks again Phillip, for the prompt reply.
As far as the way I started the application, it was really very simple and lazy way of using the STS IDE.. and run as spring boot application.. as there were junits running on start up. It created this problem.

Again, might be a silly one.. is it right to say we can ditch AsyncConfig if we want?
Cheers
Vicky

**Comment by VivekMittals** [comment]
Also as you mentioned I did the exact thing of specifying a default tenant and the problem goes away.
But then what I got confused with was that is this trigger necessary for web apps which we know will land via a typical Rest Api..

**Comment by bytefish** [comment]
Yes, you can safely remove it, when you don't plan to use ``@Async`` at all. Also make sure to delete the ``@EnableAsync`` annotation on the SpringBootApplication:

https://github.com/bytefish/SpringBootMultiTenancy/blob/f98b1963f036a329f04385fbc32dee2a7cb02c02/SpringBootMultiTenancy/src/main/java/de/bytefish/multitenancy/SampleSpringApplication.java#L21

**Comment by VivekMittals** [comment]
Perfect Phillip,
I will try this sometime this week and let you know how that went!
Cheers!
Vicky

**Comment by bytefish** [comment]
Cool, feel free to add comments here!

**Comment by bytefish** [comment]
Funny, I just tried to make the application crash by not setting a Tenant on Startup. I know this was problematic, when I wrote the article. But with JDK14 I cannot make it crash, even though I removed all properties, that prevent initialization. Weird.

How did you manage to make it run into an error?

**Comment by VivekMittals** [comment]
Hey Phillip,

I tried running some tests which has a complex DB operation like some joins etc. With that only few of the tests complained about the mentioned scenario.

Regards,
Vicky

**Comment by bytefish** [comment]
I have just taken a look at the HikariCP implementation of the shutdown method: 

* https://github.com/brettwooldridge/HikariCP/blob/009a7013cf75b69290abb9bd24b12b66b55a07bf/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L230

It already calls ``HikaiPool#softEvictConnections()`` to provide a graceful shutdown. I don't think there is much more one can do when using HikariCP. The only thing I can think of is maybe calling ``HikariPool#softEvictConnections()`` yourself and give the Queries more time to finish, by introducing a wait delay.
