### ISSUE TITLE
Subject: Parsing Command Line Arguments in .NET || Topic: Add basic arg validation

### ISSUE THREAD

**Issue by Felix-CodingClimber** [bytefish/bytefish.de#50]
First, thanks a lot for the great starting point on building my own very simple command line arg helper.

One very simple thing I added was an last parsing step, to remove options passed without an name (only - or --).

I changed the method to return an info about the parsing process:
`public static IReadOnlyList<CommandLineOption> ParseOptions(string[] arguments, out string info)
 {
 ...`

And as a very last step, I added:
 ```
// Clean up invalid options (e.g. - or -- without name)
int invalidOptions = results.RemoveAll(option => string.IsNullOrEmpty(option.Name));

info = $"Parsed <{results.Count}> valid and <{invalidOptions}> invalid command line args";
return results;
```

**Comment by bytefish** [comment]
Thanks for the feedback. Great, that it's useful. 👍 Probably one could also add some options like passing a `ParserOptions.Strict`, so it either fails with an Exception for an empty option name or just ignores empty arguments. You could also think about returning a Parse Result instead of an out Parameter like:

```
public class ParseResult 
{
    public string[] Arguments { get; set; }

    public IReadOnlyList<CommandLineOption> Result { get; set; }

    public int[] ValidArguments { get; set; }

    public int[] InvalidArguments { get; set; }
}
```

Where `ValidArguments` and `InvalidArguments` could be the indices, that are problematic.

**Comment by bytefish** [comment]
I see `System.CommandLine` is still in PREVIEW. Do you know by chance, what's the official recommendation by Microsoft for CLIE applications?
