### ISSUE TITLE
Repo is unavailable (possibly private?)

### ISSUE THREAD

**Issue by yoDon** [bytefish/bytefish.de#59]
Your [blog post on Blazor WebAssembly Cookie Authentication](https://www.bytefish.de/blog/blazor_wasm_cookie_authentication.html) mentions a repo at https://github.com/bytefish/OpenFgaExperiments but the repo doesn't seem to be publicly visible.

**Comment by bytefish** [comment]
You are right. I’ve made it private, because the OpenFGA implementation was in a semi-finished state. The responsible thing was to take it down, before anyone wastes lifetime on my wrong implementation.

I will try to extract the Cookie Auth code off of it, make a separate repository and update the repo link.
