### ISSUE TITLE
For the neo4j .Net article did you look at the neo4jclient driver?

### ISSUE THREAD

**Issue by jexp** [bytefish/bytefish.de#9]
It uses neo4j-driver under the hood but already comes with object mapping and a query DSL :)

https://github.com/Readify/Neo4jClient

Really nice article. Thanks!

**Comment by bytefish** [comment]
Yes, I looked and used the Readify Neo4jClient when starting with Neo4j. I think I switched back to the neo4j-driver, because I had performance problems... so I thought more control is necessary. But the performance problem were due to my queries, so I think porting the example to the Readify Client is useful. 😅
